CREATE TABLE "ORDERS" (
"O_NUM"	NUMBER		NOT NULL,
"L_NUM"	NUMBER		NOT NULL,
"P_UID"	VARCHAR2(200)		NOT NULL,
"O_AMOUNT"	NUMBER		NULL
);

create sequence ORDER_SEQ;



CREATE TABLE "PAYMENTS" (
	"P_UID"	VARCHAR2(200)		NOT NULL,
	"ID"	VARCHAR2(200)		NOT NULL,
	"P_POINT"	NUMBER		NULL,
	"P_AMOUNT"	NUMBER		NULL,
	"P_REALAMOUNT"	NUMBER		NULL,
	"P_REGDATE"	DATE		NULL,
	"P_METHOD"	VARCHAR2(100)		NULL,
	"P_C_NAME"	VARCHAR2(200)		NULL,
	"P_C_NUM"	NUMBER		NULL,
	"P_C_QUOTA"	NUMBER		NULL,
	"P_REMAINS"	NUMBER		NULL,
	"P_AT"	NUMBER		NULL,
	"P_RECEIPT"	VARCHAR2(400)		NULL,
	"P_C_APPLY"	NUMBER		NULL
);

commit;

SELECT * from seq;

delete sequence orders_seq;



